# .sops.yaml
keys:
  - &aljam age1gzvp3clqk5n0cqv9lts0zn68ym8xr6xxeyu8lxx5hvfkv0guu5ws7y4rel
  - &oryx age1cmqwuvuflmhg30sz5j6h9cztavahx8ep3rkshmfuqswdt0h9u48qa3x298
  - &r730xd age1wydscnqxyykujdxnpq0ekf84535dtz4vzhfz5el0h4h3us9vpusqhhctar

creation_rules:
  # Any file in the secrets folder will be encrypted so BOTH you and the server can unlock it
  - path_regex: secrets/.*$
    key_groups:
    - age:
      - *aljam
      - *oryx
      - *r730xd
