# .sops.yaml
keys:
  - &aljam ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHzrMiro1XD8krk5Kb4EWQ+rGjmgKXha/OuOmUZcopRL navi-desktop

creation_rules:
  # Any file in the secrets folder will be encrypted so BOTH you and the server can unlock it
  - path_regex: secrets/.*$
    key_groups:
    - age:
      - *aljam
