# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ed12e4ea-5204-4daf-87b4-944d2f97c5a4";
      fsType = "btrfs";
    };

  fileSystems."/run/media/aljam/Games" =
    { device = "/dev/disk/by-uuid/c68af57a-274f-408d-bdd9-58f7c203bb02";
      fsType = "btrfs";
    };

  fileSystems."/run/media/aljam/Vidya" =
    { device = "/dev/disk/by-uuid/7e38280a-0946-4d28-b888-b08e0601a2d6";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0DFC-F1C6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/369c6748-e2b5-4e5b-995f-4871b64a3b5c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
