name: Cachix

on:
  push:
    branches: [main]

jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: cachix/cachix-action@v16
        with:
          name: nixlab
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --no-link ".#nixosConfigurations.r730.config.system.build.toplevel"
